# Generated by Django 3.1.2 on 2020-12-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comics',
            new_name='Comic',
        ),
    ]
