# Generated by Django 3.1.2 on 2020-12-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='issue',
            field=models.IntegerField(verbose_name='Issue is?'),
        ),
    ]
