# Generated by Django 3.1.2 on 2020-12-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201214_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='artist',
            field=models.CharField(max_length=100, verbose_name='Artist(s)'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='issue',
            field=models.IntegerField(verbose_name='Issue No:'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='writer',
            field=models.CharField(max_length=100, verbose_name='Writer(s)'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='image',
            field=models.CharField(max_length=100, verbose_name='Cover Image URL'),
        ),
    ]
