# Generated by Django 3.1.2 on 2020-12-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201214_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('secret_identity', models.CharField(max_length=50)),
                ('power', models.TextField(max_length=250)),
            ],
        ),
    ]
