# Generated by Django 3.1.2 on 2020-12-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='heroes',
            field=models.ManyToManyField(to='main_app.Hero'),
        ),
    ]
